language: python            # this works for Linux but is an error on macOS or Windows
matrix:
  include:
    - name: "Python 3.7.1 on Xenial Linux"
      python: 3.7           # this works for Linux but is ignored on macOS or Windows
      dist: xenial          # required for Python >= 3.7
    - name: "Python 3.7.2 on macOS"
      os: osx
      osx_image: xcode10.2  # Python 3.7.2 running on macOS 10.14.3
      language: shell       # 'language: python' is an error on Travis CI macOS
    - name: "Python 3.7.3 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install: choco install python
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
install: 
  - if [[ $TRAVIS_PYTHON_VERSION == 3.7.1 ]]; then pip3 install --upgrade pip; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3.7.2 ]]; then pip3 install --upgrade pip; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3.7.3 ]]; then py -m pip install --user --upgrade pip; fi
  - pip3 install -r requirements.txt
# 'python' points to Python 2.7 on macOS but points to Python 3.7 on Linux and Windows
# 'python3' is a 'command not found' error on Windows but 'py' works on Windows only
script:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.7.1 ]]; then python okadminfinder.py; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3.7.2 ]]; then python3 okadminfinder.py; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3.7.3 ]]; then py okadminfinder.py; fi
